CREATE TABLE Pessoa(
IDPessoa integer not null,
nome varchar2(30) not null,
constraint PK_Pessoa primary key (IDPessoa)
);

CREATE SEQUENCE SQPessoa;

INSERT INTO PESSOA(IDPessoa, Nome) VALUES (SQPessoa.nextval, 'Diandra');
SELECT * FROM Pessoa;

commit;

SELECT PRODUTO.IDPRODUTO, PRODUTO.NOME FROM PRODUTO INNER JOIN ITEMPEDIDO ON PRODUTO.IDPRODUTO = PEDIDOITEM.IDPRODUTO INNER JOIN PEDIDO ON PEDIDOITEM.IDPEDIDO = PEDIDO.IDPEDIDO;

