DECLARE
    CURSOR C_ListaCli IS
   Select CIDADE.NOME From CIDADE 
GROUP BY NOME, UF  HAVING COUNT(1) > 1;

CURSOR C_ListaCliente IS
SELECT CLIENTE.NOME FROM CLIENTE INNER JOIN CIDADE ON CLIENTE.IDCIDADE = CIDADE.IDCIDADE;

BEGIN
 FOR reg IN C_ListaCliente LOOP
     DBMS_OUTPUT.PUT_LINE( reg.NOME);
   END LOOP;
   FOR reg IN C_ListaCli LOOP
     DBMS_OUTPUT.PUT_LINE( reg.NOME);
   END LOOP;

END;


  