CREATE TABLE LOGAPOSTA (
  IDLOGAPOSTA   INTEGER NOT NULL,
  IDCONCURSO    INTEGER NOT NULL,
  IDAPOSTA      INTEGER NOT NULL,
  USUARIO       VARCHAR2(30),
  DATA          DATE DEFAULT SYSDATE,  
  OPERACAO      CHAR(1) NOT NULL,
    CONSTRAINT PK_IDLOGAPOSTA
       PRIMARY KEY (IDLOGAPOSTA)
);

CREATE SEQUENCE IDLOGAPOSTA;

CREATE OR REPLACE
TRIGGER TR_AUD1_APOSTA
    AFTER INSERT OR UPDATE OR DELETE ON APOSTA
DECLARE
  V_OPERACAO CHAR(1);
  V_IDAPOSTA INTEGER;
  V_IDCONCURSO INTEGER;
BEGIN

  IF INSERTING THEN
     V_OPERACAO := 'I';
     V_IDAPOSTA := :NEW.IDAPOSTA;
     V_IDCONCURSO := :NEW.IDAPOSTA;
     
  ELSIF UPDATING THEN
     V_OPERACAO := 'U';
     V_IDAPOSTA := :OLD.IDAPOSTA;
     V_IDCONCURSO := :OLD.IDAPOSTA;
     
  ELSE
     V_OPERACAO := 'D';
     V_IDAPOSTA := :OLD.IDAPOSTA;
     V_IDCONCURSO := :OLD.IDAPOSTA;
     
  END IF;
  
  INSERT INTO LOGAPOSTA (IDCONCURSO, IDAPOSTA, DATA, USUARIO, OPERACAO)
      VALUES (V_IDAPOSTA, V_IDAPOSTA, SYSDATE, USER, V_OPERACAO);

END TR_AUD1_APOSTA;

CREATE TABLE LOGNUMERO (
  IDLOGNUMERO   INTEGER NOT NULL,
  ID_NUMERO_APOSTA      INTEGER NOT NULL,
  USUARIO       VARCHAR2(30),
  DATA          DATE DEFAULT SYSDATE,  
  OPERACAO      CHAR(1) NOT NULL,
    CONSTRAINT PK_IDLOGNUMERO 
       PRIMARY KEY (IDLOGNUMERO)
);

CREATE SEQUENCE IDLOGNUMERO;

CREATE OR REPLACE
TRIGGER TR_AUD1_NUMERO
    AFTER INSERT OR UPDATE OR DELETE ON NUMERO_APOSTA
DECLARE
  V_ID_NUMERO_APOSTA INTEGER;
  V_OPERACAO CHAR(1);
BEGIN

  IF INSERTING THEN
     V_OPERACAO := 'I';
     V_ID_NUMERO_APOSTA := :NEW.IDNUMERO_APOSTA; 
     
  ELSIF UPDATING THEN
     V_OPERACAO := 'U';
     V_ID_NUMERO_APOSTA := :OLD.IDNUMERO_APOSTA; 
     
  ELSE
     V_OPERACAO := 'D';
     V_ID_NUMERO_APOSTA := :OLD.IDNUMERO_APOSTA; 
     
  END IF;
  INSERT INTO LOGNUMERO (ID_NUMERO_APOSTA, DATA, USUARIO, OPERACAO)
      VALUES (V_ID_NUMERO_APOSTA, SYSDATE, USER, V_OPERACAO);

END TR_AUD1_NUMERO;


PROCEDURE RELATORIO(PCONCURSO IN INTEGER) IS
BEGIN

SELECT COUNT(IDAPOSTA) AS NUMEROAPOSTAS, SUM(VALOR) AS ARRECADACAO, 

END RELATORIO;