DECLARE
    
    CURSOR C_LISTACIDADES IS
     SELECT CIDADE.NOME, CIDADE.UF FROM CIDADE 
GROUP BY NOME, UF  HAVING COUNT(1) > 1;

    CURSOR C_LISTACLIENTES(PNOME IN VARCHAR2, PUF IN VARCHAR2) IS
    SELECT  CLIENTE.NOME AS NOME_CLIENTE, CLIENTE.IDCLIENTE,CIDADE.NOME AS NOME_CIDADE, CIDADE.UF FROM CLIENTE INNER JOIN CIDADE ON CLIENTE.IDCIDADE = CIDADE.IDCIDADE
    WHERE CIDADE.NOME = PNOME AND CIDADE.UF = PUF;

BEGIN
   FOR AUX IN C_LISTACIDADES LOOP
   DBMS_OUTPUT.PUT_LINE( 'CIDADE: ' || AUX.NOME );
   FOR AUX2 IN C_LISTACLIENTES(AUX.NOME, AUX.UF) LOOP
   
   DBMS_OUTPUT.PUT_LINE( 'CLIENTE: ' || AUX2.NOME_CIDADE);
   
   END LOOP;
    
   END LOOP;
END;

CREATE INDEX IX_CIDADE_NOMEUF ON CIDADE(NOME, UF);
CREATE INDEX IX_CLIENTE_CIDADE ON CLIENTE(IDCIDADE);

DECLARE
VVALORPEDIDO PEDIDO.VALORPEDIDO%TYPE;

BEGIN

  SELECT SUM(PEDIDOITEM.QUANTIDADE * PEDIDOITEM.PRECOUNITARIO)
  INTO VVALORPEDIDO
  FROM PEDIDOITEM 
  WHERE PEDIDOITEM.IDPEDIDO = :IDPEDIDO;

UPDATE PEDIDO SET VALORPEDIDO = VVALORPEDIDO WHERE IDPEDIDO = :IDPEDIDO;
END;


CREATE VIEW PRODUTOS6MESES AS
SELECT PRODUTO.IDPRODUTO, PRODUTO.NOME FROM PRODUTO WHERE IDPRODUTO NOT IN (SELECT PRODUTO.IDPRODUTO FROM PRODUTO INNER JOIN PEDIDOITEM 
ON PEDIDOITEM.IDPRODUTO = PRODUTO.IDPRODUTO INNER JOIN PEDIDO ON PEDIDO.IDPEDIDO = PEDIDOITEM.IDPEDIDO
WHERE PEDIDO.DATAPEDIDO >= TRUNC(ADD_MONTHS(SYSDATE, -6)));


BEGIN
UPDATE PRODUTO SET SITUACAO = 'I' WHERE IDPRODUTO IN (SELECT IDPRODUTO FROM PRODUTOS6MESES);

EXCEPTION
  WHEN NO_DATA_FOUND THEN 
    DBMS_OUTPUT.PUT_LINE('Produto inexistente!');
  WHEN PROGRAM_ERROR THEN 
    DBMS_OUTPUT.PUT_LINE('Erro interno!');
END;

BEGIN
SELECT SUM(PRODUTOMATERIAL.QUANTIDADE), MATERIAL.DESCRICAO FROM MATERIAL INNER JOIN PRODUTOMATERIAL ON PRODUTOMATERIAL.IDMATERIAL = MATERIAL.IDMATERIAL
INNER JOIN PRODUTO ON PRODUTO.IDPRODUTO = PRODUTOMATERIAL.IDPRODUTO INNER JOIN PEDIDOITEM ON PEDIDOITEM.IDPRODUTO = PRODUTO.IDPRODUTO INNER JOIN
PEDIDO ON PEDIDOITEM.IDPEDIDO = PEDIDO.IDPEDIDO GROUP BY PEDIDO.IDPEDIDO;
END;

  