CREATE PROCEDURE EXERCICIO01 AS
BEGIN

DECLARE

  CURSOR CIDADES IS
       SELECT NOME, UF
       FROM   CIDADE
       GROUP  BY NOME, UF
       HAVING COUNT(1) >1;
       
  CURSOR CLIENTES (PNOME IN VARCHAR2,
                     PUF   IN VARCHAR2) IS
     SELECT CLI.IDCLIENTE,
            CLI.NOME AS NOME_CLIENTE,
            CID.NOME AS NOME_CIDADE,
            CID.UF
     FROM   CLIENTE CLI
      INNER JOIN CIDADE CID ON CID.IDCIDADE = CLI.IDCIDADE
     WHERE  CID.NOME = PNOME
     AND    CID.UF   = PUF;
     
BEGIN

  FOR C IN CIDADES LOOP     
      DBMS_OUTPUT.PUT_LINE('Cidade: '|| C.NOME );
      FOR I IN CLIENTES (C.NOME, C.UF) LOOP
           DBMS_OUTPUT.PUT_LINE('Cliente: '|| I.NOME_CLIENTE );
      END LOOP;
  END LOOP;

END;
END;

CREATE INDEX IX_CIDADE_NOMEUF   ON CIDADE (NOME,UF);
CREATE INDEX IX_CLIENTE_CIDADE  ON CLIENTE (IDCIDADE);


CREATE OR REPLACE PROCEDURE EXERCICIO02 (PIDPEDIDO IN NUMBER) AS
BEGIN

DECLARE
VVALORPEDIDO PEDIDO.VALORPEDIDO%TYPE;

BEGIN

  SELECT SUM(PEDIDOITEM.QUANTIDADE * PEDIDOITEM.PRECOUNITARIO)
  INTO VVALORPEDIDO
  FROM PEDIDOITEM 
  WHERE PEDIDOITEM.IDPEDIDO = PIDPEDIDO;
  
  EXCEPTION
  When no_data_found Then 
    DBMS_OUTPUT.PUT_LINE('Cliente inexistente!');

UPDATE PEDIDO SET VALORPEDIDO = VVALORPEDIDO WHERE IDPEDIDO = PIDPEDIDO;

END;
END;


CREATE VIEW PRODUTOS6MESES AS
SELECT PRODUTO.IDPRODUTO, PRODUTO.NOME FROM PRODUTO WHERE IDPRODUTO NOT IN (SELECT PRODUTO.IDPRODUTO FROM PRODUTO INNER JOIN PEDIDOITEM 
ON PEDIDOITEM.IDPRODUTO = PRODUTO.IDPRODUTO INNER JOIN PEDIDO ON PEDIDO.IDPEDIDO = PEDIDOITEM.IDPEDIDO
WHERE PEDIDO.DATAPEDIDO >= TRUNC(ADD_MONTHS(SYSDATE, -6)));


CREATE OR REPLACE PROCEDURE EXERCICIO03 AS
BEGIN

UPDATE PRODUTO SET SITUACAO = 'I' WHERE IDPRODUTO IN (SELECT IDPRODUTO FROM PRODUTOS6MESES);

EXCEPTION
  WHEN NO_DATA_FOUND THEN 
    DBMS_OUTPUT.PUT_LINE('Produto inexistente!');
  WHEN PROGRAM_ERROR THEN 
    DBMS_OUTPUT.PUT_LINE('Erro interno!');
END;